# `ignore`: Specify a list of regular expressions.
# Toodles will ignore a file that matches any of the entires
ignore:
- test.js
- stack-work
# `flags` specify other keywords you might want to scan other than TODO
# Hardcoded ones include TODO, FIXME, and XXX
flags:
- MAYBE
