# Putting a .toodles.yaml file in the root of your repo will give toodles
# any project specific configuration you'd like to set.

# `ignore`: Specify a list of regular expressions.
# Toodles will ignore a file that matches any of the entires
ignore:
- test.js
- stack-work
- node_modules
- Spec.hs
- venv
# `flags` specify other keywords you might want to scan other than TODO
# Hardcoded ones include TODO, FIXME, and XXX
flags:
- MAYBE
