name:                toodles
version:             0.1.0.0
github:              "aviaviavi/toodles"
license:             MIT
author:              "Avi Press"
maintainer:          "mail@avi.press"
copyright:           "2018 Avi Press"

extra-source-files:
- README.md
- web/js/app.js
- web/js/*
- web/html/*
- web/css/*
- web/fonts/*

synopsis:            Manage the TODO entries in your code
description:         See the README on GitHub at <https://github.com/aviaviavi/toodles#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  toodles:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - megaparsec
    - directory
    - filepath
    - MissingH
    - cmdargs
    - strict
    - servant
    - servant-blaze
    - blaze-html
    - servant-server
    - transformers
    - aeson
    - yaml
    - wai
    - warp
    - http-types
    - bytestring
    - regex-posix

# tests:
#   toodles-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - toodles
